INSERT INTO Categories (name) VALUES ('Furniture');
INSERT INTO Categories (name) VALUES ('Wall Decorations');
INSERT INTO Categories (name) VALUES ('Lighting');
INSERT INTO Categories (name) VALUES ('Textiles');
INSERT INTO Categories (name) VALUES ('Flooring');
INSERT INTO Categories (name) VALUES ('Outdoor Decor');
INSERT INTO Categories (name) VALUES ('Tableware');
INSERT INTO Categories (name) VALUES ('Storage Solutions');
INSERT INTO Categories (name) VALUES ('Art Pieces');
INSERT INTO Categories (name) VALUES ('Mirrors');